Repository Riverscapes/riverscapes-tools, pull requests merged in 2021-02, with the labels that each got.

#219 HOTFIX numpy version adjustment for ubuntu users fixes #218
  requirements.txt
Labels: :beetle: bug

#227 Fixed invalid geoms and buffer splitting issue.
  packages/gnat/gnat/confinement.py
Labels: pkg:GNAT

#203 February Release
  lib/commons/rscommons/__init__.py
  lib/commons/rscommons/__version__.py
  lib/commons/rscommons/classes/rs_project.py
  lib/commons/rscommons/classes/tempfiles.py
  lib/commons/rscommons/classes/vector_datasource.py
  lib/commons/rscommons/debug.py
  lib/commons/rscommons/dotenv.py
  lib/commons/rscommons/download.py
  lib/commons/rscommons/hand.py
  lib/commons/rscommons/vector_ops.py
  lib/commons/setup.py
  lib/commons/test/test_dotenv.py
  lib/commons/test/test_vector_base.py
  packages/brat/sqlbrat/__version__.py
  packages/brat/sqlbrat/brat_rs.py
  packages/gnat/.vscode/launch.json
  packages/gnat/gnat/__version__.py
  packages/gnat/gnat/confinement.py
  packages/gnat/gnat/confinement_rs.py
  packages/rscontext/.vscode/launch.json
  packages/rscontext/rscontext/__version__.py
  packages/rscontext/rscontext/bankfull.py
  packages/rscontext/rscontext/rs_context.py
  packages/rvd/database/data/ConversionLevels.csv
  packages/rvd/database/data/ConversionProportions.csv
  packages/rvd/database/data/ConversionTypes.csv
  packages/rvd/database/data/DepartureLevels.csv
  packages/rvd/database/data/intersect/Conversions.csv
  packages/rvd/database/rvd_schema.sql
  packages/rvd/rvd/__version__.py
  packages/rvd/rvd/lib/classify_conversions.py
  packages/rvd/rvd/rvd.py
  packages/rvd/rvd/rvd_report.py
  packages/rvd/rvd/rvd_rs.py
  packages/vbet/.vscode/launch.json
  packages/vbet/scripts/__init__.py
  packages/vbet/scripts/subprocess.py
  packages/vbet/setup.py
  packages/vbet/vbet/__version__.py
  packages/vbet/vbet/vbet.py
  packages/vbet/vbet/vbet_network.py
  packages/vbet/vbet/vbet_outputs.py
  packages/vbet/vbet/vbet_raster_ops.py
  packages/vbet/vbet/vbet_report.py
  packages/vbet/vbet/vbet_rs.py
  requirements.txt
  scripts/automation/FargateAllTools.sh
  scripts/automation/FargateBRAT.sh
  scripts/automation/FargateConfinement.sh
  scripts/automation/FargateRSContext.sh
  scripts/automation/FargateRSContextVBET.sh
  scripts/automation/FargateRVD.sh
  scripts/automation/FargateVBET.sh
  scripts/automation/README.md
  scripts/automation/fiveminutes.sh
  scripts/automation/maintenance.sh
Labels: enhancement

#231 unifying parameters fixes #230
  lib/commons/rscommons/build_network.py
  packages/brat/.vscode/launch.json
  packages/brat/sqlbrat/brat_build.py
  packages/brat/sqlbrat/brat_run.py
  packages/gnat/.vscode/launch.json
  packages/gnat/gnat/confinement.py
  packages/rscontext/.vscode/launch.json
  packages/rscontext/rscontext/rs_context.py
  packages/rvd/.vscode/launch.json
  packages/rvd/rvd/rvd.py
  packages/vbet/.vscode/launch.json
  packages/vbet/vbet/vbet.py
  packages/vbet/vbet/vbet_network.py
  scripts/automation/FargateAllTools.sh
  scripts/automation/FargateBRAT.sh
  scripts/automation/FargateConfinement.sh
  scripts/automation/FargateRSContext.sh
  scripts/automation/FargateRSContextVBET.sh
  scripts/automation/FargateRVD.sh
  scripts/automation/FargateVBET.sh
Labels: :beetle: bug, :fire: BLOCKED
